theme: jekyll-theme-dinky
title: Smart Group 업무기록
description: Biz History Written
subtitle: "Version 1.0"
name: "biz report"
teaser: /assets/images/office.jpg
header:
  teaser: /assets/images/note.jpg
