#theme: jekyll-theme-minimal
minimal_mistakes_skin : "default" # "air"
encoding : UTF-8
title          : "Vision and Machine learning"
subtitle : "천천히 오솔길 내듯이"
name           : "Real Coding for vision development"
description    : "openCV Study"
masthead_title : "Vision Coding"
