# theme: jekyll-theme-minimal
minimal_mistakes_skin : "air"
title: Vision and Machine learning
description: Study History
email : 'ndbb2046@naver.com'

author:
  name  : "비전개발 실전코딩"
  email : 
  links:
    - label : "Email"
      icon  : "fas fa-fw fa-envelope-square"
      url   : mailto:ndbb2046@naver.com 
